name: Deployment Verification

on: deployment_status

env:
  URNERYS: ur.caurea.org
  BUILDID: github-run-${{ github.run_id }}-${{ github.run_attempt }}

jobs:
  setup:
    if: github.event.deployment_status.state == 'success'
    runs-on: [self-hosted, nixos]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: false

      - shell: nix develop .#workflow --command bash {0}
        run: |
          curl -sf -X POST -H "Content-Type: application/json" -d '{ "id": "${{ env.BUILDID }}", "build": { "origin": { "commit": "${{ github.sha }}" } } }' "https://$URNERYS/api/v1/projects/stories/builds"

  vst:
    name: Visual Smoke Test
    if: github.event.deployment_status.state == 'success'
    runs-on: [self-hosted, nixos]
    needs: setup
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: false

      - run: nix run .#nix-develop .#workflow

      - run: ../node_modules/.bin/playwright test
        working-directory: vst
        env:
          URL: ${{ github.event.deployment_status.target_url }}

      - uses: actions/upload-artifact@v4
        with:
          name: test-results-vst
          path: test-results/
          retention-days: 7

  urnerys:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v4
        with:
          version: 8

      - run: pnpm install
      - run: ./node_modules/.bin/playwright install --with-deps chromium

      - run: ./node_modules/.bin/playwright test urnerys/*.spec.ts
        env:
          URL: ${{ github.event.deployment_status.target_url }}

      - uses: actions/upload-artifact@v4
        with:
          name: test-results-urnerys
          path: test-results/
          retention-days: 7

  seal:
    if: github.event.deployment_status.state == 'success'
    name: Deployment Verification
    runs-on: [self-hosted, nixos]
    needs:
      - vst
      - urnerys
    steps:
      - shell: nix develop .#workflow --command bash {0}
        run: |
          case "${{ github.event.deployment_status.environment }}" in
            Production)
              curl -sf -X PATCH -H "Content-Type: application/json" -d '{ "baseline": { "build": "${{ env.BUILDID }}" } }' "https://$URNERYS/api/v1/projects/stories/baselines/production"
              ;;
            *)
              curl -sf -X POST -H "Content-Type: application/json" -d '{ "check": { "baseline": "production" } }' "https://$URNERYS/api/v1/projects/stories/builds/${{ env.BUILDID }}/checks"
              ;;
          esac
