name: Update Browserslist Database

on:
  workflow_dispatch: {}
  schedule:
    - cron: "38 5 * * 2"

jobs:
  update-browserslist-database:
    name: Update Browserslist Database
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: false

      - uses: DeterminateSystems/nix-installer-action@v16
      - run: nix run github:nicknovitski/nix-develop .#workflow

      - run: pnpm up caniuse-lite
      - run: pnpm dedupe

      - uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.CREATE_PULL_REQUEST_TOKEN }}
          branch: update-browserslist-database
          title: Update Browserslist Database
          commit-message: Update Browserslist Database
