name: Urnerys

on: deployment_status

env:
  URNERYS: vrrrt.caurea.org

jobs:

  # This whole workflow only runs when the deployment was successful. The first
  # thing we do is to create a build. The action uses the current GITHUB_RUN_ID
  # as the unique build identifier.
  setup:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: urnerys/action/createBuild@main

  # After the setup is completed, we take the snapshots.
  create-snapshots:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v4
        with:
          version: 8

      - run: pnpm install
      - run: ./node_modules/.bin/playwright install --with-deps chromium

      - run: ./node_modules/.bin/playwright test --retries 3
        env:
          URL: ${{ github.event.deployment_status.target_url }}

  # If this was a preview deployment, we compare the snapshots against the baseline.
  check-build:
    needs: create-snapshots
    if: github.event.deployment_status.environment != 'Production'
    runs-on: ubuntu-latest
    steps:
      - uses: urnerys/action/checkBuild@main

  # If the deployment was done in the production environment, we move the
  # baseline, so that any future runs are compared against snapshots in this
  # build.
  move-baseline:
    needs: create-snapshots
    if: github.event.deployment_status.environment == 'Production'
    runs-on: ubuntu-latest
    steps:
      - uses: urnerys/action/moveBaseline@main
